AWSTemplateFormatVersion: '2010-09-09'
Description: Create a simple S3 bucket

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: myn-simplebucket-incloudformation-123456
